### ISSUE TITLE
add support of different S3 storage types to the chart

### ISSUE THREAD

**Issue by cheshi-mantu** [qameta/testops-deploy-helm-chart#14]
## Motivation
we have several storage types of S3 in the app, current implementation of the chart only allows usage of "S3" S3 storage type.

For optimal usage of RPM when using AWS S3 we have S3_ASYNC, that allows Delete object**s** , copy and move operations allowing 

## Requirement

Alongside with the type of the storage selection, please add the capability to pass the type of S3
- S3
- S3_ASYNC
  - and define parameters for S3_ASYNC
    - allure.blob-storage.bulkRemoveSupported: true
    - allure.blob-storage.moveSupported: true
    - allure.blob-storage.copySupported: true

```
      ALLURE_BLOBSTORAGE_BULKREMOVESUPPORTED: true
      ALLURE_BLOBSTORAGE_MOVESUPPORTED: false
      ALLURE_BLOBSTORAGE_COPYSUPPORTED: true
```

reference: https://qameta.slack.com/archives/C02EMRFAFG8/p1676355845687649

suggestions for the values.yaml section under S3
```yaml
storage:
  type: "S3"
  s3:
    advancedS3SDK
      enabled: true
      bulkRemoveSupported: true
      moveSupported: true
      copySupported: true
```
